import Foundation
import SwiftData

struct TrainingConfig: Codable, Hashable {
    var model: String                  // HF repo ID or absolute local path
    var data: String                   // dataset directory
    var fineTuneType: FineTuneType
    var iters: Int
    var batchSize: Int
    var numLayers: Int
    var learningRate: Double
    var gradAccumulationSteps: Int
    var maxSeqLength: Int
    var valBatches: Int
    var stepsPerReport: Int
    var stepsPerEval: Int
    var saveEvery: Int
    var gradCheckpoint: Bool
    var maskPrompt: Bool
    var seed: Int
    var optimizer: String              // "adamw" | "adam" | "sgd"
    var loraRank: Int
    var loraScale: Double
    var loraDropout: Double
    var loraTargetKeys: [String]
    var adapterPath: String            // absolute path
    /// Bytes — when mlx's allocator cache exceeds this, it's freed between
    /// steps. mlx-lm's TrainingArgs default is 0 (never clear) — that's bad
    /// for large models on M-series unified memory, where a multi-GB cache
    /// idles uselessly. 1 GB is a reasonable balance: tiny perf hit from the
    /// extra free()s, big memory headroom win for 27B+ models.
    var clearCacheThreshold: Int = 1_073_741_824
    /// >0 turns on a warmup → cosine-decay learning-rate schedule with this many
    /// warmup steps (0 = constant LR). Warms up to `learningRate`, then cosine-
    /// decays to 10% of it over the rest of the run — steadier early training and
    /// a better final minimum than a flat LR. mlx-lm reads this as `lr_schedule`.
    var lrScheduleWarmupSteps: Int = 0
    /// Which training algorithm to run. `.sft` (default) is mlx-lm's supervised
    /// fine-tune; `.dpo` is preference tuning via the separate `mlx-lm-lora`
    /// trainer. Default `.sft` keeps every existing config byte-identical.
    var trainMode: TrainMode = .sft
    /// DPO temperature (β). Only emitted when `trainMode == .dpo`. Lower = stays
    /// closer to the reference model; the trainer default is 0.1.
    var dpoBeta: Double = 0.1
    /// DPO loss family ("sigmoid" | "hinge" | "ipo" | "dpop"). Only emitted in
    /// DPO mode; maps to mlx-lm-lora's `dpo_cpo_loss_type` key.
    var dpoLossType: String = "sigmoid"

    static let `default` = TrainingConfig(
        // Default base is a general Instruct model — the app teaches it coding via training.
        model: "mlx-community/Llama-3.2-3B-Instruct-4bit",
        data: "",
        fineTuneType: .lora,
        iters: 600,
        batchSize: 2,
        numLayers: 16,
        learningRate: 1e-5,
        gradAccumulationSteps: 1,
        maxSeqLength: 2048,
        valBatches: 25,
        stepsPerReport: 10,
        stepsPerEval: 100,
        saveEvery: 100,
        gradCheckpoint: true,
        maskPrompt: true,
        seed: 0,
        optimizer: "adamw",
        loraRank: 8,
        loraScale: 20.0,
        loraDropout: 0.0,
        loraTargetKeys: ["self_attn.q_proj", "self_attn.v_proj"],
        adapterPath: ""
    )

    /// Render a Double so PyYAML parses it as a float, not a string. Swift prints
    /// small values in exponent form with no mantissa dot ("2e-05"), which PyYAML
    /// loads as a *string* — and mlx-lm then chokes (or silently mis-handles it).
    /// Insert ".0" so it reads as a valid YAML float ("2.0e-05").
    static func yamlNum(_ d: Double) -> String {
        var s = String(d)
        if let e = s.firstIndex(where: { $0 == "e" || $0 == "E" }),
           !s[s.startIndex..<e].contains(".") {
            s.insert(contentsOf: ".0", at: e)
        }
        return s
    }

    func renderYAML() -> String {
        // DPO is a different trainer (mlx-lm-lora) with a different config schema —
        // route it to its own renderer. The SFT path below is unchanged so its
        // output stays byte-identical.
        if trainMode == .dpo { return renderDPOYAML() }
        var lines: [String] = []
        lines.append("# Generated by LLMPro")
        lines.append("model: \"\(model)\"")
        lines.append("train: true")
        lines.append("fine_tune_type: \(fineTuneType.rawValue)")
        lines.append("data: \"\(data)\"")
        lines.append("seed: \(seed)")
        lines.append("batch_size: \(batchSize)")
        lines.append("iters: \(iters)")
        lines.append("learning_rate: \(Self.yamlNum(learningRate))")
        lines.append("num_layers: \(numLayers)")
        lines.append("grad_accumulation_steps: \(gradAccumulationSteps)")
        lines.append("max_seq_length: \(maxSeqLength)")
        lines.append("val_batches: \(valBatches)")
        lines.append("steps_per_report: \(stepsPerReport)")
        lines.append("steps_per_eval: \(stepsPerEval)")
        lines.append("save_every: \(saveEvery)")
        lines.append("grad_checkpoint: \(gradCheckpoint)")
        lines.append("mask_prompt: \(maskPrompt)")
        lines.append("adapter_path: \"\(adapterPath)\"")
        lines.append("optimizer: \(optimizer)")
        lines.append("clear_cache_threshold: \(clearCacheThreshold)")
        // Warmup → cosine-decay LR schedule. mlx-lm calls build_schedule() on this
        // and ignores `learning_rate` when present; arguments = [peak, decay_steps, end].
        if lrScheduleWarmupSteps > 0 {
            let warmup = max(1, min(lrScheduleWarmupSteps, iters - 1))
            let decaySteps = max(1, iters - warmup)
            let endLR = learningRate * 0.1
            lines.append("lr_schedule:")
            lines.append("  name: cosine_decay")
            lines.append("  warmup: \(warmup)")
            lines.append("  warmup_init: 1.0e-07")
            lines.append("  arguments: [\(Self.yamlNum(learningRate)), \(decaySteps), \(Self.yamlNum(endLR))]")
        }
        if fineTuneType != .full {
            lines.append("lora_parameters:")
            lines.append("  keys: [\(loraTargetKeys.map { "\"\($0)\"" }.joined(separator: ", "))]")
            lines.append("  rank: \(loraRank)")
            lines.append("  scale: \(Self.yamlNum(loraScale))")
            lines.append("  dropout: \(Self.yamlNum(loraDropout))")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Render the config for the `mlx-lm-lora` DPO trainer
    /// (`python -m mlx_lm_lora.train -c <file>`). Keys are spelled to match that
    /// package's `CONFIG_DEFAULTS` (train.py) — NOTE several differ from mlx-lm's
    /// SFT schema:
    ///   • `train_type`   (NOT `fine_tune_type`)
    ///   • `train_mode: dpo`
    ///   • `gradient_accumulation_steps` (NOT `grad_accumulation_steps`)
    ///   • `dpo_cpo_loss_type`, `beta`
    ///   • `fuse: false` — defaults to true, which would dump a ~1.3 GB
    ///     model.safetensors into the adapter dir on every run.
    /// `lora_parameters` only carries {rank, dropout, scale} here (the trainer's
    /// build_lora_config reads only those; the layer count comes from top-level
    /// `num_layers`, and it does not consume a `keys:` sub-key).
    private func renderDPOYAML() -> String {
        var lines: [String] = []
        lines.append("# Generated by LLMPro (DPO / mlx-lm-lora)")
        lines.append("model: \"\(model)\"")
        lines.append("train: true")
        lines.append("train_mode: dpo")
        lines.append("train_type: \(fineTuneType.rawValue)")
        lines.append("data: \"\(data)\"")
        lines.append("seed: \(seed)")
        lines.append("batch_size: \(batchSize)")
        lines.append("iters: \(iters)")
        lines.append("learning_rate: \(Self.yamlNum(learningRate))")
        lines.append("num_layers: \(numLayers)")
        lines.append("gradient_accumulation_steps: \(gradAccumulationSteps)")
        lines.append("max_seq_length: \(maxSeqLength)")
        lines.append("val_batches: \(valBatches)")
        lines.append("steps_per_report: \(stepsPerReport)")
        lines.append("steps_per_eval: \(stepsPerEval)")
        lines.append("save_every: \(saveEvery)")
        lines.append("grad_checkpoint: \(gradCheckpoint)")
        lines.append("adapter_path: \"\(adapterPath)\"")
        lines.append("optimizer: \(optimizer)")
        lines.append("beta: \(Self.yamlNum(dpoBeta))")
        lines.append("dpo_cpo_loss_type: \(dpoLossType)")
        // Must be false: `fuse` defaults to true and would write a full ~1.3 GB
        // model.safetensors into every adapter dir after training.
        lines.append("fuse: false")
        if lrScheduleWarmupSteps > 0 {
            let warmup = max(1, min(lrScheduleWarmupSteps, iters - 1))
            let decaySteps = max(1, iters - warmup)
            let endLR = learningRate * 0.1
            lines.append("lr_schedule:")
            lines.append("  name: cosine_decay")
            lines.append("  warmup: \(warmup)")
            lines.append("  warmup_init: 1.0e-07")
            lines.append("  arguments: [\(Self.yamlNum(learningRate)), \(decaySteps), \(Self.yamlNum(endLR))]")
        }
        if fineTuneType != .full {
            lines.append("lora_parameters:")
            lines.append("  rank: \(loraRank)")
            lines.append("  scale: \(Self.yamlNum(loraScale))")
            lines.append("  dropout: \(Self.yamlNum(loraDropout))")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}

@MainActor
final class TrainingService {
    static let shared = TrainingService()

    enum TrainingError: LocalizedError {
        case runtimeNotReady
        case datasetMissing
        var errorDescription: String? {
            switch self {
            case .runtimeNotReady: "Python runtime is not ready."
            case .datasetMissing: "Dataset directory does not contain train.jsonl."
            }
        }
    }

    func start(job: TrainingJob, context: ModelContext, resumeAdapterFile: URL? = nil) async throws {
        guard PythonRuntime.shared.isReady, let python = PythonRuntime.shared.pythonURL
        else { throw TrainingError.runtimeNotReady }

        let jobID = job.id
        let trainMode = job.trainMode

        // DPO runs through the separate `mlx-lm-lora` trainer, an optional add-on
        // not gated by Ready. Fresh venvs ship it; an older one installs it
        // on-demand here. If it can't be installed, fail the job with an
        // actionable message rather than spawning a missing module.
        if trainMode == .dpo, await !PythonRuntime.shared.dpoTrainerInstalled() {
            let ok = await PythonRuntime.shared.installDPOTrainer { _ in }
            if !ok {
                let msg = "The DPO trainer (mlx-lm-lora) isn't installed and couldn't be installed automatically. Check your internet connection and try again, or open Settings to reinstall the Python runtime."
                Log.error("DPO trainer install failed for job \(jobID)", .training)
                job.status = .failed
                job.endedAt = Date()
                JobRegistry.shared.register(job)
                JobRegistry.shared.markFailed(jobID: jobID, msg)
                try? context.save()
                job.writeSidecar()
                return
            }
        }

        let configURL = job.configURL
        let configYAML = job.configYAML
        let logURL = job.logURL

        try configYAML.write(to: configURL, atomically: true, encoding: .utf8)
        try? FileManager.default.createDirectory(at: job.adapterURL, withIntermediateDirectories: true)

        job.status = .running
        job.startedAt = Date()
        JobRegistry.shared.register(job)
        job.writeSidecar()

        var env: [String: String] = [
            "HF_HOME": PathResolver.hfHome.path,
            "PYTHONUNBUFFERED": "1"
        ]
        // Apply the optional MLX memory budget from the Memory tab (no-op when off).
        // SFT runs mlx-lm's `lora` subcommand; DPO runs mlx-lm-lora's `train`
        // module. Everything downstream — the stdout/stderr/exit tail tasks, the
        // NaN guard, JobRegistry wiring, the sidecar, and the auto-fuse completion
        // hook — is identical: the DPO output is a normal LoRA adapter.
        var argv: [String]
        if trainMode == .dpo {
            // mlx-lm-lora's train.py main() merges `-c <yaml>` into argparse with
            // `if getattr(args, k) is None: setattr(...)` — i.e. the YAML only
            // fills args that are STILL None after CLI parsing. Several DPO-
            // controlling args have NON-None argparse defaults, so our YAML value
            // is silently dropped and the default wins. The worst offender is
            // `--train-mode` (argparse default "sft"): our `train_mode: dpo` is
            // ignored, the dataset loader routes to SFT, and a {prompt,chosen,
            // rejected} preference set fails with "Unsupported data format for SFT
            // training" (exit 1). The others with non-None defaults are
            // `--gradient-accumulation-steps` (1), `--beta` (0.1), and
            // `--dpo-cpo-loss-type` ("sigmoid").
            //
            // Fix: pass every value that argparse would otherwise default away as
            // an explicit CLI flag (CLI args are parsed first and never
            // overwritten), and keep `-c <yaml>` ONLY for the None-default and
            // nested keys it still honors — `lora_parameters`, `lr_schedule`, and
            // `fuse: false`. The flag VALUES are read back out of the same rendered
            // config.yaml so the CLI and the on-disk record agree by construction
            // (no recompute). The config.yaml is still written above as the
            // canonical record and the source of the None-default/nested keys.
            let y = configYAML
            func req(_ key: String) -> String? { Self.yamlScalar(key, in: y) }
            // `model` and `data` are already absolute in the rendered YAML (the
            // model path was resolved by TrainingConfigView.resolveModelArg before
            // rendering) — reuse them verbatim so CLI == YAML.
            guard let model = req("model"),
                  let data = req("data"),
                  let adapterPath = req("adapter_path"),
                  let trainType = req("train_type"),
                  let iters = req("iters"),
                  let batchSize = req("batch_size"),
                  let learningRate = req("learning_rate"),
                  let numLayers = req("num_layers"),
                  let gradAccum = req("gradient_accumulation_steps"),
                  let beta = req("beta"),
                  let lossType = req("dpo_cpo_loss_type")
            else {
                // Can't honor the user's DPO settings without these — fail loudly
                // rather than spawn a run that would silently train as SFT.
                let msg = "Couldn't build the DPO training command — the generated config is missing a required field. This is an internal error; please retry, and if it persists report it."
                Log.error("DPO argv build failed for job \(jobID): missing key(s) in rendered config.yaml", .training)
                job.status = .failed
                job.endedAt = Date()
                JobRegistry.shared.markFailed(jobID: jobID, msg)
                try? context.save()
                job.writeSidecar()
                return
            }
            // Clamp the batch size to the actual preference-set size. mlx-lm-lora's
            // `iterate_dpo_batches` builds its batch index as
            // `range(0, len(rows) - batch_size + 1, batch_size)` — when
            // `batch_size > len(rows)` that range is EMPTY, so the iterator's
            // `while True:` loop yields nothing forever and the training step
            // `next(iterator)` HANGS at 100% CPU (no Iter lines, no traceback, no
            // saved adapter — the process never exits, so even the exit handler
            // never fires). The eval path (`train=False`) doesn't spin, but an empty
            // batch index there divides by zero tokens → NaN/crash. Both are avoided
            // by guaranteeing batch_size ≤ both the train and valid row counts.
            //
            // This is a real, common case: the "Teach by preference" CTA enables at
            // only 4 prefs, which split to ~3 train / 1 valid — far below the default
            // batch of 4. The CLI flag is authoritative (it's non-None, so it wins
            // over the YAML per mlx-lm-lora's merge); we also rewrite the on-disk
            // config.yaml `batch_size:` so the post-mortem record agrees with the CLI.
            let configBatch = Int(batchSize) ?? 1
            let dataDir = URL(fileURLWithPath: data)
            let trainRows = Self.jsonlRowCount(dataDir.appendingPathComponent("train.jsonl"))
            let validRows = Self.jsonlRowCount(dataDir.appendingPathComponent("valid.jsonl"))
            // Clamp to train rows AND (when a valid set exists) valid rows, so both
            // the train loop and the eval pass can form at least one full batch.
            let validFloor = validRows > 0 ? validRows : trainRows
            let effectiveBatch = max(1, min(configBatch, trainRows, validFloor))
            if effectiveBatch != configBatch {
                Log.notice("DPO batch size clamped \(configBatch)→\(effectiveBatch) for a \(trainRows)-row train / \(validRows)-row valid preference set (job \(jobID))", .training)
                // Keep config.yaml consistent with the authoritative CLI flag so a
                // post-mortem reading the on-disk record isn't misled. DPO branch
                // only — the SFT config write above is untouched.
                let patched = Self.replacingYAMLScalar("batch_size", with: "\(effectiveBatch)", in: y)
                try? patched.write(to: configURL, atomically: true, encoding: .utf8)
            }
            let batchArg = String(effectiveBatch)
            argv = [
                "-m", "mlx_lm_lora.train",
                "--train",
                "--train-mode", "dpo",
                "--train-type", trainType,
                "--model", model,
                "--data", data,
                "--adapter-path", adapterPath,
                "--iters", iters,
                "--batch-size", batchArg,
                "--learning-rate", learningRate,
                "--num-layers", numLayers,
                "--gradient-accumulation-steps", gradAccum,
                "--beta", beta,
                "--dpo-cpo-loss-type", lossType
            ]
            // `--grad-checkpoint` is argparse `store_true, default=None`: passing it
            // sets True, omitting it leaves None so the YAML `grad_checkpoint:` fills
            // it. So only pass the flag for the true case; the false case rides the
            // YAML (store_true can't express False on the CLI).
            if Self.yamlScalar("grad_checkpoint", in: y) == "true" {
                argv.append("--grad-checkpoint")
            }
            // The YAML still drives the None-default + nested keys (lora_parameters,
            // lr_schedule, fuse: false, seed, optimizer, max_seq_length, val_batches,
            // steps_per_report/eval, save_every).
            argv += ["-c", configURL.path]
            if let resumeAdapterFile {
                argv += ["--resume-adapter-file", resumeAdapterFile.path]
            }
        } else {
            argv = ["-m", "mlx_lm", "lora", "-c", configURL.path]
            if let resumeAdapterFile {
                // Continue from an existing adapter's weights (refine an earlier fine-tune).
                argv += ["--resume-adapter-file", resumeAdapterFile.path]
            }
        }
        // mlx_run.py is a generic launcher (`-m <module> <args…>`), so it pins
        // MLX's Apple-Silicon memory limits for the DPO trainer too — which
        // matters most here, since DPO holds a 2nd full reference-model copy.
        let wrapped = MemoryService.wrap(argv)
        for (k, v) in wrapped.env { env[k] = v }

        let process: RunningProcess
        do {
            process = try await ProcessRunner.spawn(
                executable: python,
                arguments: wrapped.arguments,
                environment: env
            )
        } catch {
            job.status = .failed
            JobRegistry.shared.markFailed(jobID: jobID, error.localizedDescription)
            try? context.save()
            throw error
        }

        job.pid = process.pid
        job.writeSidecar()
        JobRegistry.shared.attach(job, process: process)

        // Stream stdout AND stderr into the same log file so a post-mortem
        // (after the app has restarted, after the in-memory JobRegistry ring
        // has been GC'd) still has the actual error mlx-lm printed. Both tasks
        // are @MainActor so writes are serialized; the writer is shared via an
        // actor wrapper to keep Swift 6 strict-concurrency happy.
        FileManager.default.createFile(atPath: logURL.path, contents: nil)
        let logWriter = LogFileWriter(url: logURL)

        let stdout = process.stdout
        let stderr = process.stderr
        let exit = process.exit

        // Capture the process handle so the stdout watcher can SIGTERM it on
        // NaN loss (no point continuing — the adapter would be junk).
        let processHandle = process

        Task { @MainActor in
            for await line in stdout {
                await logWriter.append(line + "\n")
                JobRegistry.shared.recordLog(jobID: jobID, line)

                if LogStreamParser.hasNaNLoss(line) {
                    let msg = "Training produced NaN loss — the model+dataset combination is numerically unstable on this base. Try: (1) re-download the same model in fp16/bf16 instead of 8bit, (2) pick a smaller base (Qwen2.5-Coder-7B is a solid alternative), or (3) lower the Advanced learning rate."
                    await logWriter.append("[error] " + msg + "\n")
                    JobRegistry.shared.recordLog(jobID: jobID, "[error] " + msg)
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                    return
                }

                if let step = LogStreamParser.parse(line) {
                    JobRegistry.shared.recordStep(jobID: jobID, step)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.appendStep(step)
                        try? context.save()
                        job.writeSidecar()
                    }
                }
            }
        }

        Task { @MainActor in
            for await line in stderr {
                await logWriter.append("[stderr] " + line + "\n")
                JobRegistry.shared.recordLog(jobID: jobID, "[stderr] " + line)

                // Catch the specific class of errors that have a known cause
                // and surface them with an actionable message instead of the
                // generic "exit 1" the user otherwise sees.
                if line.contains("QuantizedMatmul::vjp") ||
                   line.contains("no gradient wrt the quantized weights") {
                    let msg = "Full fine-tune doesn't work on quantized (8-bit / 4-bit) weights — mlx can't compute gradients through them. Switch to LoRA or DoRA in Advanced settings, or use the bf16 / fp16 version of this model as the base."
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                }

                // Metal GPU OOM. The error string is emitted by libc++abi's
                // uncaught-exception handler when MLX's Metal command buffer
                // fails to allocate. This is DIFFERENT from system-RAM OOM:
                // Apple Silicon Metal has its own GPU working-set ceiling
                // (~110-115 GB on a 128 GB Mac) that's well below total RAM.
                // Training can hit this even though the SystemMetrics widget
                // shows "free" memory. The fix is almost always to switch from
                // full FT → LoRA, or shrink the model with the Modify tab.
                if line.contains("kIOGPUCommandBufferCallbackErrorOutOfMemory") ||
                   line.contains("[METAL] Command buffer execution failed: Insufficient Memory") {
                    let msg = "Out of GPU memory. Apple Silicon's Metal layer has its own working-set ceiling (~110 GB on a 128 GB Mac) that's separate from system RAM — the 'Memory in use' gauge may show headroom even when Metal can't allocate one more buffer. Fixes (most → least disruptive): (1) switch fine-tune type from Full to LoRA / DoRA in Advanced — for a 26B model this drops peak memory by ~80 GB. (2) Shrink the base in the Modify tab (8-bit quant halves it). (3) Reduce max_seq_length in Advanced — every halving cuts activation memory by ~50%. (4) Pick a smaller base."
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                }
            }
        }

        Task { @MainActor in
            let result: ProcessExit
            do { result = try await exit.value }
            catch { result = ProcessExit(code: -1, signal: nil) }

            // This fires when the process actually TERMINATES, for ANY reason —
            // clean exit, nonzero exit, or a signal/crash (SIGKILL from the OS
            // OOM-killer, a SIGSEGV, the user killing a stuck pid). The
            // terminationHandler that resolves `exit.value` does not distinguish
            // them beyond the status code, so anything that isn't a clean 0 is a
            // failure. The earlier DPO hang escaped this path only because the
            // process never terminated at all (the empty-batch infinite loop, now
            // prevented by the batch clamp above); a process that dies abnormally
            // has always reached here. Drive the JobRegistry/sidecar transition
            // UNCONDITIONALLY (not gated on the SwiftData re-fetch) so a job can
            // never be left stranded as `.running` when its process is gone — even
            // if the @Model record can't be re-fetched.
            let alreadyFailed = (JobRegistry.shared.jobs[jobID]?.status == .failed)
            let succeeded = (result.code == 0)
            if succeeded {
                JobRegistry.shared.markCompleted(jobID: jobID)
            } else if !alreadyFailed {
                // Distinguish a signal/crash from a plain nonzero exit in the
                // message — "killed by signal 9" is far more actionable than
                // "exit 137" for a post-mortem.
                let reason: String
                if let sig = result.signal {
                    reason = "Training stopped unexpectedly (killed by signal \(sig)). This usually means the run was force-quit or the system ran out of memory."
                } else {
                    reason = "exit \(result.code)"
                }
                JobRegistry.shared.markFailed(jobID: jobID, reason)
            }

            if let job = Self.fetchJob(id: jobID, context: context) {
                // If we already terminated this job ourselves (e.g. NaN-loss
                // fail-fast), the helpful error is already on the job and the
                // exit code is just SIGTERM noise — don't clobber it.
                if succeeded {
                    job.status = .completed
                } else if !alreadyFailed {
                    job.status = .failed
                }
                job.endedAt = Date()
                try? context.save()
                job.writeSidecar()

                // "Training should modify the model": if the user asked for it,
                // auto-fuse the freshly-trained adapter into the base model and save
                // the result as a new ready-to-use model (the original is kept).
                // Runs only on a clean success; nothing registers unless the fused
                // output validates (see ModelApplyService).
                if succeeded, job.applyToModelInPlace {
                    let repoID = job.baseModelRepoID
                    let adapterDir = job.adapterURL
                    Task { @MainActor in
                        do {
                            let newModel = try await ModelApplyService.shared.apply(repoID: repoID, adapterDir: adapterDir)
                            if let j = Self.fetchJob(id: jobID, context: context) {
                                j.applyOutcome = "Saved trained model: \(newModel.lastPathComponent)"
                                try? context.save(); j.writeSidecar()
                            }
                        } catch {
                            if let j = Self.fetchJob(id: jobID, context: context) {
                                j.applyOutcome = "Auto-fuse failed: \(error.localizedDescription)"
                                try? context.save(); j.writeSidecar()
                            }
                        }
                    }
                }
            }
        }
    }

    func resume(job: TrainingJob, latestAdapterFile: URL, context: ModelContext) async throws {
        guard PythonRuntime.shared.isReady, let python = PythonRuntime.shared.pythonURL
        else { throw TrainingError.runtimeNotReady }
        let process = try await ProcessRunner.spawn(
            executable: python,
            arguments: [
                "-m", "mlx_lm", "lora",
                "-c", job.configURL.path,
                "--resume-adapter-file", latestAdapterFile.path
            ],
            environment: ["HF_HOME": PathResolver.hfHome.path, "PYTHONUNBUFFERED": "1"]
        )
        job.status = .running
        job.pid = process.pid
        JobRegistry.shared.attach(job, process: process)
    }

    /// Find the newest LoRA checkpoint to resume from in an adapter directory.
    ///
    /// mlx-lm writes periodic checkpoints during training named with a zero-padded
    /// iteration prefix, e.g. `0000200_adapters.safetensors`, plus a final
    /// `adapters.safetensors` once the run completes. To pick up where an
    /// interrupted run left off we want the most-trained snapshot available:
    /// the highest-numbered `*_adapters.safetensors` if any exist, otherwise the
    /// plain `adapters.safetensors`, otherwise nil (nothing to resume from).
    ///
    /// Pure `FileManager` enumeration with no actor state, hence `static`.
    static func latestAdapterCheckpoint(in dir: URL) -> URL? {
        let fm = FileManager.default
        let suffix = "_adapters.safetensors"
        let entries = (try? fm.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)) ?? []
        let numbered = entries
            .filter { $0.lastPathComponent.hasSuffix(suffix) }
            .compactMap { url -> (Int, URL)? in
                let prefix = String(url.lastPathComponent.dropLast(suffix.count))
                guard let iter = Int(prefix) else { return nil }
                return (iter, url)
            }
        if let best = numbered.max(by: { $0.0 < $1.0 }) { return best.1 }
        let final = dir.appendingPathComponent("adapters.safetensors")
        return fm.fileExists(atPath: final.path) ? final : nil
    }

    private static func fetchJob(id: UUID, context: ModelContext) -> TrainingJob? {
        let descriptor = FetchDescriptor<TrainingJob>(predicate: #Predicate { $0.id == id })
        return (try? context.fetch(descriptor))?.first
    }

    /// Count the non-empty lines (rows) in a JSONL file. Used by the DPO launch to
    /// clamp the batch size to the actual preference-set size — mlx-lm-lora's batch
    /// iterator hangs when `batch_size` exceeds the row count (see the clamp in
    /// `start()`). Returns 0 if the file is missing or unreadable, which the clamp
    /// treats as "no batch possible" via its `max(1, …)` floor.
    static func jsonlRowCount(_ url: URL) -> Int {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return 0 }
        var count = 0
        text.enumerateLines { line, _ in
            if !line.trimmingCharacters(in: .whitespaces).isEmpty { count += 1 }
        }
        return count
    }

    /// Replace the value of a top-level scalar key in our own generated training
    /// YAML, preserving every other line. Mirrors `yamlScalar`'s notion of
    /// "top-level" (key at column 0, no leading space) so nested children under
    /// `lora_parameters:` / `lr_schedule:` are never touched. Used only by the DPO
    /// branch to keep the on-disk `batch_size:` consistent with the clamped CLI
    /// flag. If the key isn't present the input is returned unchanged.
    static func replacingYAMLScalar(_ key: String, with newValue: String, in yaml: String) -> String {
        let prefix = key + ":"
        var out: [String] = []
        var replaced = false
        for rawLine in yaml.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            if !replaced, line.hasPrefix(prefix) {
                out.append("\(prefix) \(newValue)")
                replaced = true
            } else {
                out.append(line)
            }
        }
        return out.joined(separator: "\n")
    }

    /// Read a single top-level scalar value out of our own generated training YAML.
    /// This is intentionally minimal — it only needs to round-trip the flat
    /// `key: value` lines that `TrainingConfig.renderDPOYAML()` emits so the DPO
    /// launch can promote those values to guaranteed-honored CLI flags (the YAML is
    /// the single source so CLI and config.yaml agree). It is NOT a general YAML
    /// parser: it matches a line whose first non-space character starts the key at
    /// column 0 (top-level only, so nested `lora_parameters:` children are skipped),
    /// strips an optional surrounding pair of double quotes, and ignores trailing
    /// `# comments`. Returns nil if the key is absent or has an empty value.
    static func yamlScalar(_ key: String, in yaml: String) -> String? {
        let prefix = key + ":"
        for rawLine in yaml.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            // Top-level keys only: a leading space means it's nested under a parent.
            guard line.hasPrefix(prefix) else { continue }
            var value = String(line.dropFirst(prefix.count))
            // Strip an inline comment only when it's clearly a comment (preceded by
            // whitespace) — values here never contain a literal " #".
            if let hashRange = value.range(of: " #") {
                value = String(value[value.startIndex..<hashRange.lowerBound])
            }
            value = value.trimmingCharacters(in: .whitespaces)
            if value.count >= 2, value.hasPrefix("\""), value.hasSuffix("\"") {
                value = String(value.dropFirst().dropLast())
            }
            return value.isEmpty ? nil : value
        }
        return nil
    }
}

/// Serialised append-only writer for training.log. Both stdout and stderr task
/// streams route through this actor so their lines never interleave mid-line
/// and writes don't race on the shared FileHandle (Swift 6 strict concurrency
/// rejects unprotected FileHandle sharing).
actor LogFileWriter {
    private let url: URL
    private var handle: FileHandle?

    init(url: URL) {
        self.url = url
        self.handle = try? FileHandle(forWritingTo: url)
        try? self.handle?.seekToEnd()
    }

    func append(_ text: String) {
        guard let data = text.data(using: .utf8) else { return }
        if handle == nil { handle = try? FileHandle(forWritingTo: url); try? handle?.seekToEnd() }
        try? handle?.write(contentsOf: data)
    }
}
