import Foundation
import SwiftData

struct TrainingConfig: Codable, Hashable {
    var model: String                  // HF repo ID or absolute local path
    var data: String                   // dataset directory
    var fineTuneType: FineTuneType
    var iters: Int
    var batchSize: Int
    var numLayers: Int
    var learningRate: Double
    var gradAccumulationSteps: Int
    var maxSeqLength: Int
    var valBatches: Int
    var stepsPerReport: Int
    var stepsPerEval: Int
    var saveEvery: Int
    var gradCheckpoint: Bool
    var maskPrompt: Bool
    var seed: Int
    var optimizer: String              // "adamw" | "adam" | "sgd"
    var loraRank: Int
    var loraScale: Double
    var loraDropout: Double
    var loraTargetKeys: [String]
    var adapterPath: String            // absolute path
    /// Bytes — when mlx's allocator cache exceeds this, it's freed between
    /// steps. mlx-lm's TrainingArgs default is 0 (never clear) — that's bad
    /// for large models on M-series unified memory, where a multi-GB cache
    /// idles uselessly. 1 GB is a reasonable balance: tiny perf hit from the
    /// extra free()s, big memory headroom win for 27B+ models.
    var clearCacheThreshold: Int = 1_073_741_824
    /// >0 turns on a warmup → cosine-decay learning-rate schedule with this many
    /// warmup steps (0 = constant LR). Warms up to `learningRate`, then cosine-
    /// decays to 10% of it over the rest of the run — steadier early training and
    /// a better final minimum than a flat LR. mlx-lm reads this as `lr_schedule`.
    var lrScheduleWarmupSteps: Int = 0

    static let `default` = TrainingConfig(
        // Default base is a general Instruct model — the app teaches it coding via training.
        model: "mlx-community/Llama-3.2-3B-Instruct-4bit",
        data: "",
        fineTuneType: .lora,
        iters: 600,
        batchSize: 2,
        numLayers: 16,
        learningRate: 1e-5,
        gradAccumulationSteps: 1,
        maxSeqLength: 2048,
        valBatches: 25,
        stepsPerReport: 10,
        stepsPerEval: 100,
        saveEvery: 100,
        gradCheckpoint: true,
        maskPrompt: true,
        seed: 0,
        optimizer: "adamw",
        loraRank: 8,
        loraScale: 20.0,
        loraDropout: 0.0,
        loraTargetKeys: ["self_attn.q_proj", "self_attn.v_proj"],
        adapterPath: ""
    )

    /// Render a Double so PyYAML parses it as a float, not a string. Swift prints
    /// small values in exponent form with no mantissa dot ("2e-05"), which PyYAML
    /// loads as a *string* — and mlx-lm then chokes (or silently mis-handles it).
    /// Insert ".0" so it reads as a valid YAML float ("2.0e-05").
    static func yamlNum(_ d: Double) -> String {
        var s = String(d)
        if let e = s.firstIndex(where: { $0 == "e" || $0 == "E" }),
           !s[s.startIndex..<e].contains(".") {
            s.insert(contentsOf: ".0", at: e)
        }
        return s
    }

    func renderYAML() -> String {
        var lines: [String] = []
        lines.append("# Generated by MLX Studio")
        lines.append("model: \"\(model)\"")
        lines.append("train: true")
        lines.append("fine_tune_type: \(fineTuneType.rawValue)")
        lines.append("data: \"\(data)\"")
        lines.append("seed: \(seed)")
        lines.append("batch_size: \(batchSize)")
        lines.append("iters: \(iters)")
        lines.append("learning_rate: \(Self.yamlNum(learningRate))")
        lines.append("num_layers: \(numLayers)")
        lines.append("grad_accumulation_steps: \(gradAccumulationSteps)")
        lines.append("max_seq_length: \(maxSeqLength)")
        lines.append("val_batches: \(valBatches)")
        lines.append("steps_per_report: \(stepsPerReport)")
        lines.append("steps_per_eval: \(stepsPerEval)")
        lines.append("save_every: \(saveEvery)")
        lines.append("grad_checkpoint: \(gradCheckpoint)")
        lines.append("mask_prompt: \(maskPrompt)")
        lines.append("adapter_path: \"\(adapterPath)\"")
        lines.append("optimizer: \(optimizer)")
        lines.append("clear_cache_threshold: \(clearCacheThreshold)")
        // Warmup → cosine-decay LR schedule. mlx-lm calls build_schedule() on this
        // and ignores `learning_rate` when present; arguments = [peak, decay_steps, end].
        if lrScheduleWarmupSteps > 0 {
            let warmup = max(1, min(lrScheduleWarmupSteps, iters - 1))
            let decaySteps = max(1, iters - warmup)
            let endLR = learningRate * 0.1
            lines.append("lr_schedule:")
            lines.append("  name: cosine_decay")
            lines.append("  warmup: \(warmup)")
            lines.append("  warmup_init: 1.0e-07")
            lines.append("  arguments: [\(Self.yamlNum(learningRate)), \(decaySteps), \(Self.yamlNum(endLR))]")
        }
        if fineTuneType != .full {
            lines.append("lora_parameters:")
            lines.append("  keys: [\(loraTargetKeys.map { "\"\($0)\"" }.joined(separator: ", "))]")
            lines.append("  rank: \(loraRank)")
            lines.append("  scale: \(Self.yamlNum(loraScale))")
            lines.append("  dropout: \(Self.yamlNum(loraDropout))")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}

@MainActor
final class TrainingService {
    static let shared = TrainingService()

    enum TrainingError: LocalizedError {
        case runtimeNotReady
        case datasetMissing
        var errorDescription: String? {
            switch self {
            case .runtimeNotReady: "Python runtime is not ready."
            case .datasetMissing: "Dataset directory does not contain train.jsonl."
            }
        }
    }

    func start(job: TrainingJob, context: ModelContext, resumeAdapterFile: URL? = nil) async throws {
        guard PythonRuntime.shared.isReady, let python = PythonRuntime.shared.pythonURL
        else { throw TrainingError.runtimeNotReady }

        let configURL = job.configURL
        let configYAML = job.configYAML
        let logURL = job.logURL
        let jobID = job.id

        try configYAML.write(to: configURL, atomically: true, encoding: .utf8)
        try? FileManager.default.createDirectory(at: job.adapterURL, withIntermediateDirectories: true)

        job.status = .running
        job.startedAt = Date()
        JobRegistry.shared.register(job)
        job.writeSidecar()

        var env: [String: String] = [
            "HF_HOME": PathResolver.hfHome.path,
            "PYTHONUNBUFFERED": "1"
        ]
        // Apply the optional MLX memory budget from the Memory tab (no-op when off).
        var argv = ["-m", "mlx_lm", "lora", "-c", configURL.path]
        if let resumeAdapterFile {
            // Continue from an existing adapter's weights (refine an earlier fine-tune).
            argv += ["--resume-adapter-file", resumeAdapterFile.path]
        }
        let wrapped = MemoryService.wrap(argv)
        for (k, v) in wrapped.env { env[k] = v }

        let process: RunningProcess
        do {
            process = try await ProcessRunner.spawn(
                executable: python,
                arguments: wrapped.arguments,
                environment: env
            )
        } catch {
            job.status = .failed
            JobRegistry.shared.markFailed(jobID: jobID, error.localizedDescription)
            try? context.save()
            throw error
        }

        job.pid = process.pid
        job.writeSidecar()
        JobRegistry.shared.attach(job, process: process)

        // Stream stdout AND stderr into the same log file so a post-mortem
        // (after the app has restarted, after the in-memory JobRegistry ring
        // has been GC'd) still has the actual error mlx-lm printed. Both tasks
        // are @MainActor so writes are serialized; the writer is shared via an
        // actor wrapper to keep Swift 6 strict-concurrency happy.
        FileManager.default.createFile(atPath: logURL.path, contents: nil)
        let logWriter = LogFileWriter(url: logURL)

        let stdout = process.stdout
        let stderr = process.stderr
        let exit = process.exit

        // Capture the process handle so the stdout watcher can SIGTERM it on
        // NaN loss (no point continuing — the adapter would be junk).
        let processHandle = process

        Task { @MainActor in
            for await line in stdout {
                await logWriter.append(line + "\n")
                JobRegistry.shared.recordLog(jobID: jobID, line)

                if LogStreamParser.hasNaNLoss(line) {
                    let msg = "Training produced NaN loss — the model+dataset combination is numerically unstable on this base. Try: (1) re-download the same model in fp16/bf16 instead of 8bit, (2) pick a smaller base (Qwen2.5-Coder-7B is a solid alternative), or (3) lower the Advanced learning rate."
                    await logWriter.append("[error] " + msg + "\n")
                    JobRegistry.shared.recordLog(jobID: jobID, "[error] " + msg)
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                    return
                }

                if let step = LogStreamParser.parse(line) {
                    JobRegistry.shared.recordStep(jobID: jobID, step)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.appendStep(step)
                        try? context.save()
                        job.writeSidecar()
                    }
                }
            }
        }

        Task { @MainActor in
            for await line in stderr {
                await logWriter.append("[stderr] " + line + "\n")
                JobRegistry.shared.recordLog(jobID: jobID, "[stderr] " + line)

                // Catch the specific class of errors that have a known cause
                // and surface them with an actionable message instead of the
                // generic "exit 1" the user otherwise sees.
                if line.contains("QuantizedMatmul::vjp") ||
                   line.contains("no gradient wrt the quantized weights") {
                    let msg = "Full fine-tune doesn't work on quantized (8-bit / 4-bit) weights — mlx can't compute gradients through them. Switch to LoRA or DoRA in Advanced settings, or use the bf16 / fp16 version of this model as the base."
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                }

                // Metal GPU OOM. The error string is emitted by libc++abi's
                // uncaught-exception handler when MLX's Metal command buffer
                // fails to allocate. This is DIFFERENT from system-RAM OOM:
                // Apple Silicon Metal has its own GPU working-set ceiling
                // (~110-115 GB on a 128 GB Mac) that's well below total RAM.
                // Training can hit this even though the SystemMetrics widget
                // shows "free" memory. The fix is almost always to switch from
                // full FT → LoRA, or shrink the model with the Modify tab.
                if line.contains("kIOGPUCommandBufferCallbackErrorOutOfMemory") ||
                   line.contains("[METAL] Command buffer execution failed: Insufficient Memory") {
                    let msg = "Out of GPU memory. Apple Silicon's Metal layer has its own working-set ceiling (~110 GB on a 128 GB Mac) that's separate from system RAM — the 'Memory in use' gauge may show headroom even when Metal can't allocate one more buffer. Fixes (most → least disruptive): (1) switch fine-tune type from Full to LoRA / DoRA in Advanced — for a 26B model this drops peak memory by ~80 GB. (2) Shrink the base in the Modify tab (8-bit quant halves it). (3) Reduce max_seq_length in Advanced — every halving cuts activation memory by ~50%. (4) Pick a smaller base."
                    JobRegistry.shared.markFailed(jobID: jobID, msg)
                    if let job = Self.fetchJob(id: jobID, context: context) {
                        job.status = .failed
                        job.endedAt = Date()
                        try? context.save()
                        job.writeSidecar()
                    }
                    processHandle.terminate()
                }
            }
        }

        Task { @MainActor in
            let result: ProcessExit
            do { result = try await exit.value }
            catch { result = ProcessExit(code: -1, signal: nil) }

            if let job = Self.fetchJob(id: jobID, context: context) {
                // If we already terminated this job ourselves (e.g. NaN-loss
                // fail-fast), the helpful error is already on the job and the
                // exit code is just SIGTERM noise — don't clobber it.
                let alreadyFailed = (JobRegistry.shared.jobs[jobID]?.status == .failed)
                if result.code == 0 {
                    job.status = .completed
                    JobRegistry.shared.markCompleted(jobID: jobID)
                } else if !alreadyFailed {
                    job.status = .failed
                    JobRegistry.shared.markFailed(jobID: jobID, "exit \(result.code)")
                }
                job.endedAt = Date()
                try? context.save()
                job.writeSidecar()
            }
        }
    }

    func resume(job: TrainingJob, latestAdapterFile: URL, context: ModelContext) async throws {
        guard PythonRuntime.shared.isReady, let python = PythonRuntime.shared.pythonURL
        else { throw TrainingError.runtimeNotReady }
        let process = try await ProcessRunner.spawn(
            executable: python,
            arguments: [
                "-m", "mlx_lm", "lora",
                "-c", job.configURL.path,
                "--resume-adapter-file", latestAdapterFile.path
            ],
            environment: ["HF_HOME": PathResolver.hfHome.path, "PYTHONUNBUFFERED": "1"]
        )
        job.status = .running
        job.pid = process.pid
        JobRegistry.shared.attach(job, process: process)
    }

    private static func fetchJob(id: UUID, context: ModelContext) -> TrainingJob? {
        let descriptor = FetchDescriptor<TrainingJob>(predicate: #Predicate { $0.id == id })
        return (try? context.fetch(descriptor))?.first
    }
}

/// Serialised append-only writer for training.log. Both stdout and stderr task
/// streams route through this actor so their lines never interleave mid-line
/// and writes don't race on the shared FileHandle (Swift 6 strict concurrency
/// rejects unprotected FileHandle sharing).
actor LogFileWriter {
    private let url: URL
    private var handle: FileHandle?

    init(url: URL) {
        self.url = url
        self.handle = try? FileHandle(forWritingTo: url)
        try? self.handle?.seekToEnd()
    }

    func append(_ text: String) {
        guard let data = text.data(using: .utf8) else { return }
        if handle == nil { handle = try? FileHandle(forWritingTo: url); try? handle?.seekToEnd() }
        try? handle?.write(contentsOf: data)
    }
}
